services:
  web:
    build: .
    container_name: cardamom_app

    ports:
      - "8000:5000"

    env_file:
      - .env

    volumes:
      - ./database:/app/database
      - ./models:/app/models
      - ./webapp/static/uploads:/app/webapp/static/uploads

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

